home/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('account/', views.account, name='account'),
    path('favorites/', views.favorites, name='favorites'),
    path('favoritesjson/<str:token>', views.favoritesjson, name='favoritesjson'),
    path('product/<int:id>', views.product, name='product'),
    path('signup/', views.signup, name='signup'),
    path('mentions/', views.mentions, name='mentions'),
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('saveproduct/<int:id>', views.saveproduct, name='saveproduct')
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

purbeurre_project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('pbadminoc/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Product(models.Model):
    """Product model created with OFFData's return data"""
    name = models.CharField(max_length=200)
    id_off = models.BigIntegerField()
    brands = models.CharField(max_length=200)
    nutrition_grade = models.CharField(max_length=1)
    satured_fat = models.FloatField()
    fat = models.FloatField()
    sugar = models.FloatField()
    salt = models.FloatField()
    categorie = models.CharField(max_length=100)
    img_url = models.URLField()
    url = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "produit"


class Profile(models.Model):
    """Proile model extending the default User model"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    favorites = models.ManyToManyField(Product, related_name='favorited', blank=True)
    api_token = models.CharField(max_length=20, null=True)
    
    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = "profile"


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create a Profile model when a User model was created"""
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    """Edit a Profile model when a User model was edited"""
    instance.profile.save()

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.urls import reverse
from django.template import loader
from .OFFData import OFFData
from .models import Product, Profile
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import validate_email
import secrets


def index(request):
    """Return Index View"""
    return render(request, 'home/index.html')


def search(request):
    """Return Search View"""
    query = request.GET.get('query')

    if not query:
        return redirect('/')

    data = OFFData(query)
    if not data.get_product():
        return render(request, 'home/noresult.html', {'query': query})

    products = data.get_substitutes()
    context = {
        'query': query,
        'product': data.product,
        'products': sorted(products, key=lambda product: product.nutrition_grade)
    }

    return render(request, 'home/search.html', context)


def favorites(request):
    """Return Favorites View"""
    if request.user.is_authenticated:
        # Create Unique Token for favorites API
        if not request.user.profile.api_token:
            request.user.profile.api_token = secrets.token_urlsafe(20)
            request.user.save()
        return render(request, 'home/favorites.html')
    return render(request, 'home/notlogged.html', status=401)

def favoritesjson(request, token):
    try:
        profile = Profile.objects.get(api_token=token)
        queryset = profile.favorites.all()
        if not queryset:
            return JsonResponse({'state': 'success', 'favorites':[]}, status=200)

        favorites = []
        for favorite in queryset:
            product = { 'id': favorite.id_off,
                        'name': favorite.name,
                        'brands': favorite.brands,
                        'nutrition_grade': favorite.nutrition_grade,
                        'saturated_fat': favorite.satured_fat,
                        'fat': favorite.fat,
                        'sugar': favorite.sugar,
                        'salt': favorite.salt,
                        'categorie': favorite.categorie,
                        'img_url': favorite.img_url,
                        'off_url': favorite.url,
                        'url': request.build_absolute_uri(reverse('home:product', kwargs={'id':favorite.id_off}))
                    }
            favorites.append(product)
        return JsonResponse({'state': 'success', 'favorites':favorites}, status=200)
    except Profile.DoesNotExist:
        return JsonResponse({'state': 'error', 'reason': 'Incorrect Token / User Not Found'}, status=400)

def account(request):
    """Return Account View"""
    if request.user.is_authenticated:
        if request.method == 'POST' and 'emailchange' in request.POST:
            try:
                validate_email(request.POST.get('email'))
                request.user.email = request.POST.get('email')
                request.user.save()
            except Exception:
                pass
        return render(request, 'home/account.html')
    return render(request, 'home/notlogged.html', status=401)


def signup(request):
    """Return Signup View"""
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'home/signup.html', {'form': form})


def product(request, id):
    """Return Product View"""
    product = get_object_or_404(Product, id_off=id)
    context = {
        'product': product,
        'nutriscore': ['A', 'B', 'C', 'D', 'E']
    }
    return render(request, 'home/product.html', context)


def saveproduct(request, id):
    """Save or remove a product from a User's profile"""
    if request.user.is_authenticated:
        # Check if not already fav
        try:
            product = request.user.profile.favorites.get(id_off=id)
        except Product.DoesNotExist:
            try:
                product = Product.objects.get(id_off=id)
                request.user.profile.favorites.add(product)
                return JsonResponse({'state': 'success', 'action': 'added'}, status=200)
            except Product.DoesNotExist:
                return JsonResponse({'state': 'error', 'reason': 'Product does not exist', 'action': 'added'}, status=400)

        request.user.profile.favorites.remove(product)
        return JsonResponse({'state': 'success', 'action': 'removed'}, status=200)
    else:
        return JsonResponse({'state': 'error', 'reason': 'User not logged in', 'action': 'null'}, status=400)


def mentions(request):
    """Return Mentions View"""
    return render(request, 'home/mentions.html')

home/templates/home/account.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Mon Compte{% endblock %}
{% block content %}
  <header id="banner" class="masthead text-center text-white d-flex h-25">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>{{user.username}}</strong>
            </h1>
          </div>
        </div>
      </div>
    </header>

    <section class="minh-75">
      <div class="container">
        <div class="row justify-content-center">
          <div class="text-center form-wrap">
            <p>Afin d'être avertie de la sortie de notre site dans sa version 2, nous vous proposons d'enregistrer votre adresse email.</p>
            <form action="" method="post">
              {% csrf_token %}
              <p>
                <input type="field" name="email" placeholder="username@domain.com" value="{{request.user.email}}">
              </p>
              <input type="submit" class="col col-2 align-self-center btn btn-custom btn-md btn-primary text-white" name="emailchange" value="Enregistrer" />
            </form>
          </div>

        </div>
      </div>
    </section>

{% endblock %}

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" href="{% static 'home/img/favicon.png' %}" />

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'home/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'home/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">

    <!-- Plugin CSS -->
    <link href="{% static 'home/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'home/css/creative.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/main.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <img id="logo" src="{% static 'home/img/logo.png' %}" class="img-fluid">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'home:index' %}">Pur Beurre</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <form action="{% url 'home:search' %}" method="get" accept-charset="utf-8">
                <input type="text" name="query" class="mt-1" placeholder="Recherche">
              </form>
            </li>
            {% if not user.is_authenticated %}
            <li class="nav-item" title="Se connecter">
              <a class="nav-link js-scroll-trigger" href="#" data-toggle="modal" data-target="#myModal"><i class="fa fa-sign-in fa-lg"></i></a>
              {% else %}
              <li class="nav-item" title="Mon Compte">
                <a class="nav-link js-scroll-trigger" href="{% url 'home:account' %}"><i class="fa fa-user fa-lg"></i></a>
              </li>
              <li class="nav-item" title="Mes Aliments">
                <a class="nav-link js-scroll-trigger" id="carrot" href="{% url 'home:favorites' %}"></a>
              </li>
              <li class="nav-item" title="Se déconnecter">
                <a class="nav-link js-scroll-trigger" href="{% url 'home:logout' %}?next={{ request.path }}"><i class="fa fa-sign-out fa-lg"></i></a>
              {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {%block content %}{%endblock%}

    <footer class="page-footer font-small bg-dark text-white pt-3 mt-4 py-3">
      <div class="container-fluid text-center text-md-left">
        <div class="row">
          <div class="col-md-6 text-center">
            <a class="text-uppercase" href="{% url 'home:mentions' %}">Mentions Légales</a>
          </div>
          <div class="col-md-6 text-center">
            <a class="text-uppercase" href="{% url 'home:index' %}#contact">Contact</a>
          </div>
        </div>
      </div>
      
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'home/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'home/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'home/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'home/vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'home/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'home/js/creative.min.js' %}"></script>
    {%block script %}{%endblock%}
<!-- Showing only if user not logged -->
  {% if not user.is_authenticated %}
    {% include 'home/loginform.html'%}
  {% endif %}

  </body>
</html>

home/templates/home/favorites.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Mes Aliments{% endblock %}
{% block content %}
  <header id="banner" class="masthead text-center text-white d-flex h-25">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>Vos favoris</strong>
            </h1>
          </div>
        </div>
      </div>
    </header>

    <section id="result" class="minh-75">
      <div class="container">
        {% if user.profile.favorites.all %}
        <div class="row mb-4">
          <a class="input-group-btn mx-auto" href="{% url 'home:favoritesjson' token=user.profile.api_token %}">
            <button class="btn btn-primary btn-xl">Exporter en JSon</button>
          </a>
        </div>
        {% endif %}
        <div id="listing" class="row">
          {% if not user.profile.favorites.all %}
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">Aucun aliment trouvé</h2>
            <h4>Afin d'en ajouter à vos favoris:
              <li>Utilisez la barre de recherche en haut de l'écran</li>
              <li>Trouver un aliment qui vous plait</li>
              <li>Enfin, cliqué sur "Enregistrer" :)</li>
              </h4>
            <hr class="my-4">
          </div>
          {% else %}
          {% for product in user.profile.favorites.all %}
          <div class="card col-lg-4 col-md-12 p-2">
            <img class="card-img-top" src={{product.img_url}} alt="Card image cap">
            <div class="card-body">
              <p class="nutriscore text-white">{{product.nutrition_grade.upper}}</p>
              <h5 class="card-title"><a href="{% url 'home:product' id=product.id_off %}">{{product.name}}</a></h5>
              <p class="card-text">{{product.brands}}</p>
            </div>
          </div>
          {% endfor %}
          {% endif %}
        </div>
      </div>
    </section>

{% endblock %}

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Accueil{% endblock %}
{% block content %}
  <header class="masthead text-center text-white d-flex">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>Du gras, oui, mais de qualité !</strong>
            </h1>
            <hr>
          </div>
          <div class="col-lg-8 mx-auto">
            <h2 class="mb-5">Trouvez un produit de substitution pour ceux que vous consommez tous les jours.</h2>
          </div>
          <div class="col-lg-8 mx-auto">
            <form class="text-center" action="{% url 'home:search' %}" method="get" accept-charset="utf-8">
              <div class="input-group">
                <input id="searchbar" name="query" type="text" class="form-control input-xxl" placeholder="Produit">
                <span class="input-group-btn">
                  <button class="btn btn-primary btn-xl" href="{% url 'home:search' %}">Chercher</button>
                </span>
              </div>
            </form>
          </div>
        </div>
      </div>
    </header>

    <section class="bg-primary text-white" id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">Colette et Remy</h2>
            <hr class="my-4">
          </div>
          <div class="col-lg-8 text-center mx-auto">
            <div>
              Pur Beurre est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et Rémy, que vous avez déjà certainement rencontrés dans notre excellent restaurant Ratatouille. 
            </div>
          </div>          
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-12 text-center">
            <div class="service-box mt-5 mx-auto">
              <img src="{% static 'home/img/colette.png' %}" class="img-fluid">
              <h3 class="mb-3">Colette</h3>
            </div>
          </div>
          <div class="col-lg-6 col-md-12 text-center">
            <div class="service-box mt-5 mx-auto">
              <img src="{% static 'home/img/remy.png' %}" class="img-fluid">
              <h3 class="mb-3">Remy</h3>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section id="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading">Contactez-nous</h2>
            <hr class="my-4">
            <p class="mb-5">Une question ? Un problème ? Nous nous tenons à votre disposition !</p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4 ml-auto text-center">
            <i class="fa fa-phone fa-3x mb-3 sr-contact"></i>
            <p>123-456-6789</p>
          </div>
          <div class="col-lg-4 mr-auto text-center">
            <i class="fa fa-envelope-o fa-3x mb-3 sr-contact"></i>
            <p>
              <a href="mailto:your-email@your-domain.com">feedback@PurBeurre.com</a>
            </p>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

home/templates/home/loginform.html
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Connexion</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      </div>

      <div class="modal-body">
        <form action="" method="post">
          {% csrf_token %}
          <p id="login">
            {% for field in request.login_form %}
            {{ field.errors }}
            {{ field.label_tag}}
            {{ field }}
            {% endfor %}
          </p>
            <input type="submit" class="btn btn-custom btn-md btn-block bg-primary text-white" name="login-modal" value="Se connecter" />
        </form>
        <div class="text-center">
          <label>
            <a href="{% url 'home:signup' %}">Créer un compte</a>
          </label>
        </div>
      </div>
    </div>
  </div>
</div>

home/templates/home/noresult.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Aucun résultat{% endblock %}
{% block content %}
  <header id="banner" class="masthead text-center text-white d-flex h-25">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>Aucun résultat</strong>
            </h1>
          </div>
        </div>
      </div>
    </header>

    <section id="result" class="minh-75">
      <div class="container">
        <div id="listing" class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">Malheureusement, nous n'avons trouvé aucun résultat :/</h2>
            <hr class="my-4">
          </div>
        </div>
      </div>
    </section>
{% endblock %}
{% block script %}
    <script src="{% static 'home/js/favorite.js' %}"></script>
{% endblock %}

home/templates/home/notlogged.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Page inaccessible{{query}}{% endblock %}
{% block content %}
  <header id="banner" class="masthead text-center text-white d-flex h-25">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>Erreur</strong>
            </h1>
          </div>
        </div>
      </div>
    </header>

    <section id="result" class="minh-75">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">Afin d'accéder à cette page, il est necessaire de se connecter !</h2>
            <hr class="my-4">
          </div>
        </div>
      </div>
    </section>

{% endblock %}

home/templates/home/product.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Fiche d'information: {{product.name}}{% endblock %}
{% block content %}
  <header id="banner" class="masthead text-center text-white d-flex h-25"  style="background-image:url('{{product.img_url}}')">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h2 class="text-uppercase">
              <strong>{{product.name}}</strong>
            </h2>
          </div>
        </div>
      </div>
    </header>

    <section id="result" class="minh-75">
      <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-12 mb-3 text-center">
              <h3>Nutriscore</h3>
              <div>
                {% for score in nutriscore %}
                  {% if score == product.nutrition_grade.upper %}
                    <strong class="selected">{{score}}</strong> 
                  {% else %}
                    {{score}}
                  {% endif %}
                {% endfor %}
              </div>
            </div>
            <div class="col-lg-6 col-md-12 text-center">
              <h3>Repère Nutritionnels pour 100g</h3>
              <p>Matières grasses / Lipides: {{product.fat}}g</p>   
              <p>Acides gras saturés: {{product.satured_fat}}g</p>
              <p>Sucres: {{product.sugar}}g</p>
              <p>Sel: {{product.salt}}g</p>
            </div>  
            <a class="col-lg-12 mt-3 text-center" href="{{product.url}}"><button class="btn btn-primary btn-xl">Voir la fiche d'OpenFoodFacts</button></a>
            </div>        
        </div>
      </div>
    </section>

{% endblock %}

home/templates/home/search.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Resultat: {{query}}{% endblock %}
{% block content %}
  <header id="banner" class="masthead text-center text-white d-flex h-25"  style="background-image:url('{{product.img_url}}')">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>{{query}}</strong>
            </h1>
          </div>
        </div>
      </div>
    </header>

    <section id="result" class="minh-75">
      <div class="container">
        <div id="listing" class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">Vous pouvez remplacez cet aliment par:</h2>
            <hr class="my-4">
          </div>
          {% for product in products %}
          <div class="card col-lg-4 col-md-12 pl-3 pr-3 pt-3 mb-3">
            <img class="card-img-top mh-100" src={{product.img_url}} alt="Card image cap">
            <div class="card-body text-center">
              <p class="nutriscore text-white">{{product.nutrition_grade.upper}}</p>
              <h5 class="card-title"><a href="{% url 'home:product' id=product.id_off %}">{{product.name}}</a></h5>
              <p class="card-text">{{product.brands}}</p>
              {% if user.is_authenticated %}
                {% if product in user.profile.favorites.all %}
                  <button type="button" name="{{product.id_off}}" class="btn btn-primary mt-2"><i class="fa fa-trash fa-lg"></i>  Supprimer</button>
                {% else %}
                  <button type="button" name="{{product.id_off}}" class="btn btn-primary mt-2"><i class="fa fa-save fa-lg"></i>  Enregistrer</button>
                {% endif %}
              {% endif %}
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>
{% endblock %}
{% block script %}
    <script src="{% static 'home/js/favorite.js' %}"></script>
{% endblock %}

home/templates/home/signup.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Inscription{% endblock %}
{% block content %}
  <header id="banner" class="masthead text-center text-white d-flex h-25">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>Inscription</strong>
            </h1>
          </div>
        </div>
      </div>
    </header>

    <section id="login" class="minh-75">
    <div class="container">
      <div class="row">
          <div class="col-xs-12 text-center mx-auto">
              <div class="form-wrap">
                <h1>Choisissez un nom d'utilisateur et un mot de passe</h1>
                <form method="post" id="signup-form" autocomplete="off">
                  {% csrf_token %}
                  {% for field in form %}
                  <p>
                    {{ field.label_tag }}<br>
                    {{ field }}
                    {% for error in field.errors %}
                    <div class="alert alert-warning">{{ error }}</div>
                    {% endfor %}
                  </p>
                  {% endfor %}
                  <input type="submit" id="btn-login" class="btn btn-custom btn-lg btn-block bg-primary text-white" value="S'inscrire">
                </form>
              </div>
        </div>
      </div>
    </div>
</section>

{% endblock %}

purbeurre_project/home/templates/home/notlogged.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Page inaccessible{{query}}{% endblock %}
{% block content %}
  <header id="banner" class="masthead text-center text-white d-flex h-25">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>Erreur</strong>
            </h1>
          </div>
        </div>
      </div>
    </header>

    <section id="result" >
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">Afin d'accéder à cette page, il est necessaire de se connecter !</h2>
            <hr class="my-4">
          </div>
        </div>
      </div>
    </section>

{% endblock %}